# This is a basic workflow to help you get started with Actions

name: Laravel for Hoster

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Cache composer dependencies
        id: cache-vendor
        uses: actions/cache@v2
        with:
          path: vendor/
          key: ${{ hashFiles('**/composer.lock') }}  
      
      - name: Install composer dependencies
        if: steps.cache-vendor.outputs.cache-hit != 'true'
        run: >
          composer install 
          -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress 
          --prefer-dist --no-dev 
          
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      
      
      - name: Cache npm dependencies
        id: cache-npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ hashFiles('package-lock.json') }}
      
      - name: Install npm dependencies
        # if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci
      
      - name: Compile the assets
        run: npm run production

      - name: Create TAR file
        run: tar --exclude ".git*" --exclude="node_modules" --exclude="storage" -czf /tmp/artifact.tar.gz .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            /tmp/artifact.tar.gz